# Generated by Django 6.0.6 on 2026-07-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelDificultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('multiplicador', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('compatibilidad', models.CharField(help_text='Ej: Peugeot 206, 207, Partner', max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horas_estimadas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_reales', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recargo_mora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descripcion_adicional', models.TextField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('dificultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.niveldificultad')),
                ('repuestos_utilizados', models.ManyToManyField(blank=True, to='api.repuesto')),
                ('tipo_trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipotrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=50)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='api.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='trabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='api.vehiculo'),
        ),
    ]
