# Generated by Django 6.0.6 on 2026-07-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='kilometraje',
            field=models.IntegerField(default=0, help_text='Km del vehículo al ingresar'),
        ),
    ]
