# Generated by Django 6.0.6 on 2026-07-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trabajo_kilometraje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='pagado',
        ),
    ]
