# Generated by Django 6.0.6 on 2026-07-19 18:37

from django.db import migrations

def cargar_marcas_argentina(apps, schema_editor):
    Marca = apps.get_model('api', 'Marca')
    
    # Lista de marcas más comunes
    marcas = [
        'Volkswagen', 'Renault', 'Peugeot', 'Ford', 'Chevrolet', 
        'Fiat', 'Toyota', 'Citroën', 'Honda', 'Nissan', 'Jeep', 'Audi', 'BMW'
    ]
    
    for nombre in marcas:
        Marca.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_marca_vehiculo_marca_fk_modelo_vehiculo_modelo_fk'),
    ]

    operations = [
        migrations.RunPython(cargar_marcas_argentina),
    ]
