# Generated by Django 6.0.6 on 2026-07-19 18:49

from django.db import migrations


def cargar_modelos_argentina(apps, schema_editor):
    Marca = apps.get_model('api', 'Marca')
    Modelo = apps.get_model('api', 'Modelo')
    
    # Catálogo de marcas y sus modelos más habituales
    catalogo = {
        'Volkswagen': ['Gol', 'Amarok', 'Vento', 'Polo', 'Bora', 'Suran', 'Up!', 'Saveiro'],
        'Renault': ['Clio', 'Kangoo', 'Sandero', 'Duster', 'Logan', 'Megane', 'Fluence'],
        'Peugeot': ['208', '207', '206', '308', 'Partner', '408'],
        'Ford': ['Ranger', 'Fiesta', 'Focus', 'Ka', 'EcoSport', 'F-100'],
        'Chevrolet': ['Corsa', 'Classic', 'Onix', 'S10', 'Cruze', 'Tracker', 'Agile'],
        'Fiat': ['Cronos', 'Palio', 'Siena', 'Uno', 'Toro', 'Fiorino', 'Argo', 'Strada'],
        'Toyota': ['Hilux', 'Corolla', 'Etios', 'Yaris'],
        'Mercedes': ['Sprinter', 'Clase A'] # ¡Acá está Mercedes!
    }
    
    for nombre_marca, modelos in catalogo.items():
        # Buscamos la marca o la creamos si no existe
        marca_obj, created = Marca.objects.get_or_create(nombre=nombre_marca)
        
        for nombre_modelo in modelos:
            Modelo.objects.get_or_create(marca=marca_obj, nombre=nombre_modelo)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cargar_marcas_comunes'),
    ]

    operations = [
        migrations.RunPython(cargar_modelos_argentina),
    ]
