# Generated by Django 6.0.6 on 2026-07-19 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cargar_modelos_comunes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='modelo',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='marca_fk',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='modelo_fk',
            new_name='modelo',
        ),
    ]
