# Generated by Django 6.0.6 on 2026-07-19 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cargar_modelos_comunes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca_fk',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='modelo_fk',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.modelo'),
        ),
    ]
