# Generated by Django 6.0.6 on 2026-09-08 01:40

import uuid
from django.db import migrations

def asignar_uuids(apps, schema_editor):
    Cliente = apps.get_model('api', 'Cliente')
    Trabajo = apps.get_model('api', 'Trabajo')
    Pago = apps.get_model('api', 'Pago')

    for modelo in [Cliente, Trabajo, Pago]:
        for fila in modelo.objects.filter(uuid__isnull=True):
            fila.uuid = uuid.uuid4()
            fila.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cliente_uuid_pago_uuid_trabajo_uuid'),
    ]

    operations = [
        migrations.RunPython(asignar_uuids),
    ]